version: '0.1'
services:
    llama.cpp:
        image: jammy_arc770:latest
        container_name: jammy_arc770
        volumes:
            - ./llama.cpp-b2906:/llama.cpp
            - ./llama.cpp.scripts:/llama.cpp.scripts
        devices:
            - /dev/dri:/dev/dri
        command: /bin/bash -c "/llama.cpp.scripts/compile_llama.sh"